application: homeawesomation
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /api(.*)
  script: appengine.main.app
  secure: always
    
- url: /static
  static_dir: static
  secure: always

libraries:
- name: webapp2
  version: latest
