application: homeawesomation
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /channel/.*
  script: appengine.main.app
    
- url: /
  static_dir: static

libraries:
- name: webapp2
  version: latest
