application: homeawesomation
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: .*
  script: appengine.main.app
  secure: always

libraries:
- name: webapp2
  version: latest
