application: homeawesomation
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /channel/.*
  script: appengine.main.app
  secure: always
  login: required

- url: /device.*
  script: appengine.main.app
  secure: always
  login: required
  
- url: /user
  script: appengine.main.app
  secure: always
    
- url: /
  static_dir: static
  secure: always
  
- url: /
  static_files: static/index\.html
  upload: static/index\.html
  secure: always

libraries:
- name: webapp2
  version: latest
